### PR TITLE
Add file existence checks and try/catch fallbacks for read errors

### PR DESCRIPTION
**Pull request by asilluron**

### CODE REVIEW

**Comment by ca77y** [comment]
this task is in coffeescript. i will add you changes in cs and push them

**Comment by ptamarit** [comment]
@ca77y you might want to add the option `header: true` to your `coffee` task's config. It will add a "Generated by CoffeeScript" header to the JS file, making it more clear that the file is no to be edited.

**Comment by ca77y** [comment]
yep, my bad. i will put it in the readme as well

**Comment by asilluron** [comment]
Welp, should have seen the CS source!

Anyway, will be helpful to see that in the Readme and file headers for sure.

**Comment by ca77y** [comment]
after some thought:
- file existance check -> i've changed it so now the task should fail. the paths included in the task under src should all be templates and so all files. if not it's a configuration error and the task should not continue processing templates.
- fallbacks -> if the template or local can't be read then the task will not complete successfully. in that case i want the build to fail as it will be corrupted anyway

i'm open to see a use case which would sway me the other way :)

**Comment by asilluron** [comment]
@ca77y Thanks for updating the coffee source. 

I agree that it should fail. The issue I was running into was grunt.file.expand relies, which I think relies on node's file functions, was having a problem at some point in recognizing folders with "."s in them. So the ideal fallback would be to have an option of "isFile" in the grunt-task. 

That way { isFile:true } would simply gloss over anything odd picked up by the pattern that wasn't an actual file.

**Comment by ca77y** [comment]
personally i'm against silently skipping anything that is in the srcs. it's
either a valid file or an mistake and shouldn't be there but i'll check how
other tasks handle this problem and i will replicate whatever is the common
rule.

On Thu, Dec 5, 2013 at 5:23 AM, Andrew G. Silluron <notifications@github.com

**Pull request closed without merging**
