### PR TITLE
Change for installation from npm.

### PR DESCRIPTION
**Pull request by katsew**
remove src/ directory which has grunt task file from .npmignore.
rename src/ to tasks/
Grunt task directory's name should be "tasks" when it comes to npm install.
change load task directory of Grunt.coffee.

### CODE REVIEW

**Comment by ca77y** [comment]
please check the module that comes from npm. it has a 'tasks' folder with i18n.js in it. the idea is to develop in cs but to publish in js. that way the js users dont need to install cs compiler.

**Comment by katsew** [comment]
@ca77y 
Thanks for your reply.
The idea is great and I agree with it.
I think the problem is, in my environment, there is no tasks directory generated.

In my package.json, I do like this
  "devDependencies": {
    "grunt-i18n": "git://github.com/ca77y/grunt-i18n.git"
 }

then I do "npm install" and in my node_modules/ directory, I have your module's directory as a "grunt-i18n".
However, there is no tasks directory generated.
How can I get through this problem?

Thanks.

**Comment by ca77y** [comment]
you can use the module in npm like this:

```
"devDependencies": {
    "grunt-i18n": "~0.3.0"
}
```

**Comment by ca77y** [comment]
you have a good point that now ppl cant take the latest version from github. it might be a good idea to include js when i push to github.

**Pull request closed without merging**
